name: Build Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Build
      run: swift build -v
#    - name: Run tests
#      run: swift test --enable-code-coverage -v
#    - name: Setup Xcode
#      uses: maxim-lobanov/setup-xcode@v1.4.0
#      with:
#          xcode-version: "13.2.1"
     - name: Run tests
      run: swift test --enable-code-coverage

     - name: Test coverage
       uses: maxep/spm-lcov-action@0.3.0
     with:
      output-file: ./coverage/lcov.info

