name: Build Package

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Test coverage
      uses: maxep/spm-lcov-action@0.3.0
      with:
          output-file: ./coverage/lcov.info



          


#    - name: Setup Xcode
#      uses: maxim-lobanov/setup-xcode@v1.4.0
#      with:
#          xcode-version: "13.2.1"
#    - name: Gather code coverage
#      run: xcrun llvm-cov export -format="lcov" .build/debug/Package3PackageTests.products.xctest/Contents/MacOS/Package3PackageTests.product -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

